apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: events-exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: 0.0.0
  name: kube-events-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-events-exporter
subjects:
- kind: ServiceAccount
  name: kube-events-exporter
  namespace: default
